[tool.poetry]
name = "main"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7.1, <3.12"

dep = { path = "../dep" }
numpy = ">=1.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
